rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - <your email address>
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.0
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.21
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.0.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.1.1

